---
- hosts: common
  remote_user: root
  roles:
    - common

- hosts: sparkngin1
  roles:
    - zookeeper_test
    - sparkngin

- hosts: sparkngin2
  roles:
    - hdp
    - zookeeper_test
    - zookeeper
    - kafka
    - play-framework
    - mysql-server
    - kafka-web-console
    - kafka-offset-monitor